### PR TITLE
Fixes layout calculation problems for Firefox and Safari

### PR DESCRIPTION
**Pull request by johannheyne**
In Firefox the this.gutter value is sometimes a bit different. That causes in some use cases a this.cols calculation result lower than the expected. Using Math.round instead of Math.floor fixes this problem here and outputs the correct this.cols value.

There was a problem in calculation of the colSpan:
Firefox: operator % produces in some cases results > "1"
Safari: operator % produces in some cases "1" as result

### CODE REVIEW

**Comment by NicolasGraph** [comment]
Will this [issue](http://jsfiddle.net/qfgwmL0q/5/) be fixed in the future to easily play with frameworks?

**Comment by johannheyne** [comment]
desandro fixed it in an separate branch
https://github.com/desandro/masonry/tree/overshoot

**Comment by dipson** [comment]
@desandro Any reason why your overshoot branch has not been merged into master yet?

**Comment by desandro** [comment]
I've merged the `overshoot` fix into master. Masonry v3.2.3 has the pixel rounding fix. Give it a shot!

Thanks again for this contribution. Moving on! :racehorse:

**Pull request closed without merging**
